/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Program = IDL.Variant({
  'mba' : IDL.Null,
  'mca' : IDL.Null,
  'phd' : IDL.Null,
  'mtech' : IDL.Null,
  'btech' : IDL.Null,
});
export const Enquiry = IDL.Record({
  'cityState' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'yearOfPassing' : IDL.Nat,
  'timestamp' : Time,
  'specialization' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'program' : Program,
});

export const idlService = IDL.Service({
  'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
  'submitEnquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Program, IDL.Text, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Program = IDL.Variant({
    'mba' : IDL.Null,
    'mca' : IDL.Null,
    'phd' : IDL.Null,
    'mtech' : IDL.Null,
    'btech' : IDL.Null,
  });
  const Enquiry = IDL.Record({
    'cityState' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'yearOfPassing' : IDL.Nat,
    'timestamp' : Time,
    'specialization' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'program' : Program,
  });
  
  return IDL.Service({
    'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
    'submitEnquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Program, IDL.Text, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };