/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Enquiry {
    cityState: string;
    fullName: string;
    email: string;
    yearOfPassing: bigint;
    timestamp: Time;
    specialization: string;
    phoneNumber: string;
    program: Program;
}
export enum Program {
    mba = "mba",
    mca = "mca",
    phd = "phd",
    mtech = "mtech",
    btech = "btech"
}
export interface backendInterface {
    getAllEnquiries(): Promise<Array<Enquiry>>;
    submitEnquiry(fullName: string, email: string, phoneNumber: string, cityState: string, program: Program, specialization: string, yearOfPassing: bigint): Promise<void>;
}
import type { Enquiry as _Enquiry, Program as _Program, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllEnquiries(): Promise<Array<Enquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEnquiries();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEnquiries();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitEnquiry(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Program, arg5: string, arg6: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitEnquiry(arg0, arg1, arg2, arg3, to_candid_Program_n6(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitEnquiry(arg0, arg1, arg2, arg3, to_candid_Program_n6(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
            return result;
        }
    }
}
function from_candid_Enquiry_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Enquiry): Enquiry {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Program_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Program): Program {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cityState: string;
    fullName: string;
    email: string;
    yearOfPassing: bigint;
    timestamp: _Time;
    specialization: string;
    phoneNumber: string;
    program: _Program;
}): {
    cityState: string;
    fullName: string;
    email: string;
    yearOfPassing: bigint;
    timestamp: Time;
    specialization: string;
    phoneNumber: string;
    program: Program;
} {
    return {
        cityState: value.cityState,
        fullName: value.fullName,
        email: value.email,
        yearOfPassing: value.yearOfPassing,
        timestamp: value.timestamp,
        specialization: value.specialization,
        phoneNumber: value.phoneNumber,
        program: from_candid_Program_n4(_uploadFile, _downloadFile, value.program)
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mba: null;
} | {
    mca: null;
} | {
    phd: null;
} | {
    mtech: null;
} | {
    btech: null;
}): Program {
    return "mba" in value ? Program.mba : "mca" in value ? Program.mca : "phd" in value ? Program.phd : "mtech" in value ? Program.mtech : "btech" in value ? Program.btech : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Enquiry>): Array<Enquiry> {
    return value.map((x)=>from_candid_Enquiry_n2(_uploadFile, _downloadFile, x));
}
function to_candid_Program_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Program): _Program {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Program): {
    mba: null;
} | {
    mca: null;
} | {
    phd: null;
} | {
    mtech: null;
} | {
    btech: null;
} {
    return value == Program.mba ? {
        mba: null
    } : value == Program.mca ? {
        mca: null
    } : value == Program.phd ? {
        phd: null
    } : value == Program.mtech ? {
        mtech: null
    } : value == Program.btech ? {
        btech: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
